### ISSUE TITLE
Everything is frozen on Arch 64

### ISSUE THREAD

**Issue by abderraouf-adjal** [Swordfish90/cool-retro-term#109]
Everything is frozen, even the menus

This what I see: http://i.imgur.com/TbnrGOc.png

I install it from Arch Linux "yaourt"

$ uname -a
Linux ins-3537 3.16.1-1-ARCH #1 SMP PREEMPT Thu Aug 14 07:40:19 CEST 2014 x86_64 GNU/Linux

CPU: i5-4200U
GPU: Intel HD Graphics 4400, i915

KDE 4.14.0

**Comment by Scimmia22** [comment]
abderraouf-adjal, is this still an issue? A lot of people are using this on Arch right now without any problems.

**Comment by abderraouf-adjal** [comment]
@Scimmia22 
I'm not using Arch now.
But `cool-retro-term` work with Ubuntu 14.04

**Comment by Swordfish90** [comment]
I think we can close this. If this is still valid for someone please post here and I'll reopen it.
