### ISSUE TITLE
Launch an instance of cool-retro-term with a given command as argument

### ISSUE THREAD

**Issue by iqualfragile** [Swordfish90/cool-retro-term#119]
cool-retro-term htop
opens a new empty cool retro term, but not htop in it am i missing something or is this application missing that feature?

**Comment by DeutscheGabanna** [comment]
I have this script that is supposed to use the new options `--program` and `-c`
```
#!/bin/bash

 source $HOME/.bash_profile
 source $HOME/.bashrc

 WORKDIR="$HOME/scripts"

 cool-retro-term \
    --fullscreen \
    --workdir "$WORKDIR" \
    -pr "$HOME/.local/share/cool-retro-term/profiles/custom.json" \
    --program $HOME/miniconda3/bin/conda
    -c "run -n base filetags '$1'"
```

However, I get the following error:
`/home/deutschegabanna/scripts/taggify-no-bash.sh: line 13: -c: command not found`
