### ISSUE TITLE
Text pasted from CRT shows as .VCF attachment in Mac Mail.app

### ISSUE THREAD

**Issue by esoffron** [Swordfish90/cool-retro-term#202]
Chalk this up as a strange one, but I report it only because I love CRT so much!

If I cut and paste some text from CRT into a Mail.app new mail message it shows up as PastedContact-x.vcf, but the text is correct if pasted into other applications like TextEdit, TextWrangler, or even Microsoft Word.  Attached is a picture showing what I mean.  Text pasted from other applications works as expected.  There must be some metadata being sent with the clipboard that Mail interprets differently than the other applications do.

This could well be a Mail.app bug.

I first noticed this with the pre-packaged RC download, but when I rebuilt from source I see the same problem.

Thanks for making such a cool tool!

![new_message_and_document1_and_microsoft_word](https://cloud.githubusercontent.com/assets/4109731/5648696/5a6718dc-965e-11e4-9554-e67b6981ed3f.png)

**Comment by Swordfish90** [comment]
I don't know what to say... This is just really strange :) ... You are probably right: this looks like we are sending some metadata which are parsed in a strange way. I just made some quick tests and it doesn't seem to be directly inherited from Qt. Thank you for spotting this!

Of course as you probably understand the priority of this is low, but I'll look into it.

**Comment by esoffron** [comment]
Definitely low priority, but interesting... thanks for checking it out!

**Comment by doug-baer** [comment]
This happens when I copy any text from a Microsoft Remote Desktop session into Mail as well, so not a CRT-specific issue.

**Comment by esoffron** [comment]
You are absolutely correct!  

For what it's worth, still happens in 10.10.2 14C106a (beta from 1/21/2015).  Sounds like a Radar needs to be filed with Apple -- CRT is innocent!

**Comment by esoffron** [comment]
I put it in with Apple as bug report 19563669.  That and a nickel will get you a cup of coffee, but I tried...

**Comment by Swordfish90** [comment]
That's a really good news. I love closing issues without writing a single line of code. @doug-baer Thanks for pointing that out.

**Comment by doug-baer** [comment]
No problem. It has been driving me nuts for days and I didn't want anyone else to have to chase that ghost.
