### ISSUE TITLE
Does not set icon for self in Xorg

### ISSUE THREAD

**Issue by tomchiverton** [Swordfish90/cool-retro-term#205]
(KDE4, Ubuntu 14.04 LTS) displays the icon for the app in the toolbar and window frame as the default Xorg one. Note the menu entry created by the Debian package is fine.

I've no idea where to set it in the package (a cmake macro needed ?) Or does the code listen for an X message ? and Google is being unhelpful.

**Comment by KAMiKAZOW** [comment]
Apparently @Swordfish90 simply forgot to set it for the window. cool-retro-term.desktop also still has the generic Terminal icon.

**Comment by Swordfish90** [comment]
@KAMiKAZOW I was just typing that :D ... Anyway he is right we just need to set it to the window.

**Comment by KAMiKAZOW** [comment]
And install it in the icons in the first place. Or is it my packaging that's borked and therefore does not install the CRT icon?

**Comment by Swordfish90** [comment]
@KAMiKAZOW Your packaging is fine. Icons are currently not installed because I don't know which is the proper way to do that (taking into account differences in DEs). The best idea is probably to see what other qt applications are doing.

**Comment by KAMiKAZOW** [comment]
Install them into /usr/share/icons/hicolor/[resolution]/apps
Make sure the install script all renames the current crt64.png,… to cool-retro-term.png when installing them.

When setting the window icon, it should also load that icon and not hardcore the bitmap or anything as alternative icon themes with a designated new CRT icon would not be loaded then.

**Comment by KAMiKAZOW** [comment]
An alternative, though worse, way would be to install the icon into the pixmaps directory. That way, however, multiple resolutions would not be supported.

In the meantime I'll modify cool-retro-term.spec for the hicolor approach.

**Comment by tomchiverton** [comment]
The Debian packages do create a new menu entry with the apps icon.

I'm talking about the little icon in the top right, or in the task bar.

**Comment by Swordfish90** [comment]
@KAMiKAZOW I just pushed the changes into a separate branch: https://github.com/Swordfish90/cool-retro-term/tree/install-icons . Please give it a go and let me know.
@tomchiverton This is really strange since the icon is never set in the application.

**Comment by KAMiKAZOW** [comment]
Tom is prabably meaning that the default terminal icon is used in the launcher.

**Comment by KAMiKAZOW** [comment]
![6](https://cloud.githubusercontent.com/assets/3259076/5713348/75fe4528-9abb-11e4-99f0-2a5b7162ecd9.png)
\o/

**Comment by KAMiKAZOW** [comment]
Btw I believe both Pixmaps and Hicolor are not needed. Highcolor should be enough but I guess it does not hurt to have both approaches either…

**Comment by tomchiverton** [comment]
@Swordfish90 the Debian package explicitly copies the images and patches the .desktop file. The changes on that branch look like the cross-platform equivalent. 
If you merge them I'll update ?

**Comment by Swordfish90** [comment]
@tomchiverton That explains everything. I'll merge them tonight, and you should update the package, so that everyone can benefit from this.
@KAMiKAZOW Actually we need them both as unity looks for the icon in the pixmap directory.
Thank you both for your help!

**Comment by KAMiKAZOW** [comment]
That can't be true. If it were true most applications under Ubuntu would have no icon.

**Comment by Swordfish90** [comment]
@KAMiKAZOW Don't mind me I'm an idiot :D ... When I tried yesterday I just forgot to update the icon cache so the icon was just blank but the pixmap worked. 

I'm closing the issue since everything is now in master.

**Comment by tomchiverton** [comment]
Hmm. Something not right with either the qmake config (my qmake voodoo is weak) or something I need to find in the packaging... 
https://launchpadlibrarian.net/194920745/buildlog_ubuntu-trusty-i386.cool-retro-term_0.97-2~trusty1ubuntu5_FAILEDTOBUILD.txt.gz
```
.
.
.
install -m 644 -p /build/buildd/cool-retro-term-0.97/app/icons/256x256/cool-retro-term.png /build/buildd/cool-retro-term-0.97/debian/cool-retro-term/usr/share/icons/hicolor/256x256/apps/
make[2]: Leaving directory `/build/buildd/cool-retro-term-0.97/app'
install -m 644 -p /build/buildd/cool-retro-term-0.97/cool-retro-term.desktop /build/buildd/cool-retro-term-0.97/debian/cool-retro-term/usr/share/applications/
make[1]: Leaving directory `/build/buildd/cool-retro-term-0.97'
   dh_install
cp: cannot stat 'debian/tmp/app/icons/crt256.png': No such file or directory
dh_install: cp -a debian/tmp/app/icons/crt256.png debian/cool-retro-term//usr/share/app-install/icons// returned exit code 1
make: *** [binary] Error 2
dpkg-buildpackage: error: /usr/bin/fakeroot debian/rules binary gave error exit status 2
```

**Comment by Swordfish90** [comment]
The icons have been moved into a different location and renamed. The package fails looking for a crt256.png (which has been renamed to cool-retro-term.png and moved into a different folder). You should updated the paths in the debian package.
