### ISSUE TITLE
Bountysource

### ISSUE THREAD

**Issue by x-a-n-a-x** [Swordfish90/cool-retro-term#206]
Hi.
Thanks for making this amazing terminal. 

I think you should consider adding Bounties to your Github issues pages. 
Please, add the Github plugin to let people to place bounties on their favorite issues (and will help you get indirect donations). 

Once installed, the plugin will make your github page look like that:
https://github.com/OpenRA/OpenRA/issues?direction=desc&labels=bounty&page=1&sort=updated&state=open

Summary of bounties on your Bountysource page: 
https://www.bountysource.com/teams/cool-retro-term/issues

---

Bountysource faq: https://www.bountysource.com/faq
Bountysource blog: http://blog.bountysource.com/

Here is doc (about how to integrate it on github): 
http://blog.bountysource.com/post/48954271533/improved-github-integration-automatically-update

**Comment by Swordfish90** [comment]
Hi. I'm really glad you and enjoying CRT. I've never used Bountysource before, but I think it might be nice addition. Thank you for the suggestion.

**Comment by x-a-n-a-x** [comment]
And once you have added the Bountysource integration onto your Github Issues pages, I think README.md could be modified (at the bottom, in "Donations") to let users know they can donate this way.

**Comment by Swordfish90** [comment]
@x-a-n-a-x ... Bountysource is officially integrated into the project!
