### ISSUE TITLE
Core dump in settings

### ISSUE THREAD

**Issue by cowens** [Swordfish90/cool-retro-term#21]
While modifying the effects settings, the app froze and eventually dumped core:

> file:///home/cowens/src/cool-old-term/app/SettingsEffectsTab.qml:56:13: QML CheckableSlider: Binding loop detected for property "value"
qmlscene: ../../src/xcb_conn.c:186: write_vec: Assertion `!c->out.queue_len' failed.
./cool-old-term: line 4:  1178 Aborted                 (core dumped) qmlscene -I imports app/main.qml

I believe I had just enabled screen distortion and was attempting to increase bloom.

**Comment by Swordfish90** [comment]
I'm closing this issue since it's not related to CRT.
