### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by jak645** [Swordfish90/cool-retro-term#22]
on ubuntu 14.04 i install manually Qt5.3 i open your project whit .pro file when i try to compile Qmake show me error 3

Cannot read /home/mederic/Téléchargements/cool-old-term/app/app.pro: No such file or directory
MAKEFILE_GENERATOR variable not set as a result of parsing : app.pro. Possibly qmake was not able to find files included using "include(..)" - enable qmake debugging to investigate more.
13:18:21: Le processus "/home/mederic/Qt/5.3/gcc/bin/qmake" s'est terminé avec le code 3.

Erreur lors de la compilation/déploiement du projet cool-old-term (kit : Desktop Qt 5.3 GCC 32bit)
Lors de l'exécution de l'étape "qmake"

Code 3 (https://qt-project.org/wiki/qmake-exit-codes)
The project file could not be evalutated correctly, or the meta file generator failed. (i.e. the meta files could not be created)

can you send a compiled version of your cool project =) thx

**Comment by Swordfish90** [comment]
The PPA packages for ubuntu are now available. I'm closing this issue.
