### ISSUE TITLE
Instructions: Make CRT default terminal

### ISSUE THREAD

**Issue by 7ranceaddic7** [Swordfish90/cool-retro-term#226]
So, I really love this program and have finally figured out how to make it my default (<Ctl>+<Alt>+T) terminal.  Still need to figure out how to get it to launch from nautilus with  'Open in Terminal'.

I hope I've done this correctly; please modify if needed.
# Make cool-retro-term launcher available in dash

sudo cp cool-retro-term.desktop /usr/share/applications/
# Move the icons; home for <user>

sudo cp -R /home/<user>/cool-retro-term/app/icons /usr/share/icons/cool-retro-term/
# modify desktop entry, your <editor> of choice

sudo <editor> /usr/share/applications/cool-retro-term.desktop

```
Exec=cool-retro-term -to- Exec=/usr/share/applications/cool-retro-term.desktop
Icon=cool-retro-term -to- Icon=/usr/share/icons/cool-retro-term/icons/<choose size, recommend:128x128>/cool-retro-term.png
```
# make it executable

sudo chmod +x /usr/share/applications/cool-retro-term.desktop
# Move to local user share

sudo cp -R ~/cool-retro-term/ /usr/local/share/
# Set as default terminal

gsettings set org.gnome.desktop.default-applications.terminal exec /usr/local/share/cool-retro-term/cool-retro-term

You may/may not need to log to get the gsetting to stick.  I did.  After that, <Ctl>+<Alt>+T should now launch CRT.
##

**Comment by Swordfish90** [comment]
@7ranceaddic7 Executing "sudo make install" after the build step should automatically take care of copying the binary, the icons, the desktop file and the plugin in the proper locations. Thank you for suggesting how to set it as the default terminal.

**Comment by timbeach** [comment]
Along these lines, I've set cool-retro-term as my default terminal on arch linux running i3 window manager. 
Is there a way to set my custom profile as the default when it first loads?
Thanks in advance!

**Comment by ldtr-dev** [comment]
### **How to add _cool-retro-term_ as Nautilus 'Open in Terminal' terminal - (Tested in Ubuntu 20.04)**

I know it's been years but...
> @7ranceaddic7  "... Still need to figure out how to get it to launch from nautilus with 'Open in Terminal'. ..."

I was struggling trying to do it, I finally did it using [nautilus-open-any-terminal](https://github.com/Stunkymonkey/nautilus-open-any-terminal).

1. First, we install prerequisites:
`sudo apt-get update -y && sudo apt-get install python-nautilus && sudo apt-get install python3-nautilus`

2. Then we can install nautilus-open-any-terminal:
`pip install nautilus-open-any-terminal && nautilus -q && glib-compile-schemas /usr/share/glib-2.0/schemas`

3. We proceed installing [dconf-editor](https://wiki.gnome.org/Apps/DconfEditor) to provide our new terminal information.
`sudo apt-get update && sudo apt-get install dconf-editor`

4. We open the GUI of dconf-editor and go to the `com/github/stunkymonkey/nautilus-open-any-terminal` folder.
5. We edit the nautilus-open-any-terminal parameters as follows:
`(flatpack = 'system'), (keybindings = '<Ctrl><Alt>t'), (new-tab = True), (terminal = 'cool-retro-term')`
6. Done! Now we can open Nautilus and when we right click our folder there'll be the "Open Cool-Retro-Term here" option.

### Optional - Uninstall gnome-terminal

When we right-click Nautilus file explorer there'll still being the option for opening the current folder using gnome-terminal, we can fix this uninstalling it.

- **For uninstalling**
`sudo apt-get remove gnome-terminal && nautilus -q`

- **For reinstalling**
`sudo apt-get install gnome-terminal`

Hope all this info is useful!

**Comment by SeriousConcept1134** [comment]
> ### **How to add _cool-retro-term_ as Nautilus 'Open in Terminal' terminal - (Tested in Ubuntu 20.04)**
> 
> I know it's been years but...
> 
> > [@7ranceaddic7](https://github.com/7ranceaddic7)  "... Still need to figure out how to get it to launch from nautilus with 'Open in Terminal'. ..."
> 
> I was struggling trying to do it, I finally did it using [nautilus-open-any-terminal](https://github.com/Stunkymonkey/nautilus-open-any-terminal).
> 
>     1. First, we install prerequisites:
>        `sudo apt-get update -y && sudo apt-get install python-nautilus && sudo apt-get install python3-nautilus`
> 
>     2. Then we can install nautilus-open-any-terminal:
>        `pip install nautilus-open-any-terminal && nautilus -q && glib-compile-schemas /usr/share/glib-2.0/schemas`
> 
>     3. We proceed installing [dconf-editor](https://wiki.gnome.org/Apps/DconfEditor) to provide our new terminal information.
>        `sudo apt-get update && sudo apt-get install dconf-editor`
> 
>     4. We open the GUI of dconf-editor and go to the `com/github/stunkymonkey/nautilus-open-any-terminal` folder.
> 
>     5. We edit the nautilus-open-any-terminal parameters as follows:
>        `(flatpack = 'system'), (keybindings = '<Ctrl><Alt>t'), (new-tab = True), (terminal = 'cool-retro-term')`
> 
>     6. Done! Now we can open Nautilus and when we right click our folder there'll be the "Open Cool-Retro-Term here" option.
> 
> 
> ### Optional - Uninstall gnome-terminal
> 
> When we right-click Nautilus file explorer there'll still being the option for opening the current folder using gnome-terminal, we can fix this uninstalling it.
> 
>     * **For uninstalling**
>       `sudo apt-get remove gnome-terminal && nautilus -q`
> 
>     * **For reinstalling**
>       `sudo apt-get install gnome-terminal`
> 
> 
> Hope all this info is useful!

Very useful, thank you! Is there any way to make the name more clean? i.e. instead of "Open cool-retro-term here", just have it say "Open Terminal Here" ?
