### ISSUE TITLE
Build Error "reference to ‘Filter’ is ambiguous"

### ISSUE THREAD

**Issue by PatBee** [Swordfish90/cool-retro-term#229]
I was really looking forward to an amber monitor.  But after installing dependencies and trying to make, I get the following.  Sadly I don't have time to trouble shoot. Should qmake-qt5 have produced output?

------
[root@ansibletst1 cool-retro-term]# qmake-qt5
[root@ansibletst1 cool-retro-term]# make 
cd qmltermwidget/ && ( test -e Makefile || /usr/bin/qmake-qt5 /usr/local/src/cool-retro-term/qmltermwidget/qmltermwidget.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory `/usr/local/src/cool-retro-term/qmltermwidget'
g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -D_REENTRANT -Wall -W -fPIC -DHAVE_POSIX_OPENPT -DHAVE_SYS_TIME_H -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../../lib64/qt5/mkspecs/linux-g++ -I. -Ilib -Isrc -I../../../../include/qt5 -I../../../../include/qt5/QtQuick -I../../../../include/qt5/QtWidgets -I../../../../include/qt5/QtGui -I../../../../include/qt5/QtQml -I../../../../include/qt5/QtNetwork -I../../../../include/qt5/QtCore -I. -o BlockArray.o lib/BlockArray.cpp
lib/BlockArray.cpp: In member function ‘bool Konsole::BlockArray::setHistorySize(size_t)’:
lib/BlockArray.cpp:234: warning: ignoring return value of ‘int ftruncate(int, __off_t)’, declared with attribute warn_unused_result
g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -D_REENTRANT -Wall -W -fPIC -DHAVE_POSIX_OPENPT -DHAVE_SYS_TIME_H -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../../lib64/qt5/mkspecs/linux-g++ -I. -Ilib -Isrc -I../../../../include/qt5 -I../../../../include/qt5/QtQuick -I../../../../include/qt5/QtWidgets -I../../../../include/qt5/QtGui -I../../../../include/qt5/QtQml -I../../../../include/qt5/QtNetwork -I../../../../include/qt5/QtCore -I. -o ColorScheme.o lib/ColorScheme.cpp
g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -D_REENTRANT -Wall -W -fPIC -DHAVE_POSIX_OPENPT -DHAVE_SYS_TIME_H -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../../lib64/qt5/mkspecs/linux-g++ -I. -Ilib -Isrc -I../../../../include/qt5 -I../../../../include/qt5/QtQuick -I../../../../include/qt5/QtWidgets -I../../../../include/qt5/QtGui -I../../../../include/qt5/QtQml -I../../../../include/qt5/QtNetwork -I../../../../include/qt5/QtCore -I. -o Emulation.o lib/Emulation.cpp
g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -D_REENTRANT -Wall -W -fPIC -DHAVE_POSIX_OPENPT -DHAVE_SYS_TIME_H -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../../lib64/qt5/mkspecs/linux-g++ -I. -Ilib -Isrc -I../../../../include/qt5 -I../../../../include/qt5/QtQuick -I../../../../include/qt5/QtWidgets -I../../../../include/qt5/QtGui -I../../../../include/qt5/QtQml -I../../../../include/qt5/QtNetwork -I../../../../include/qt5/QtCore -I. -o Filter.o lib/Filter.cpp
lib/Filter.cpp:93: error: reference to ‘Filter’ is ambiguous
lib/Filter.h:394: error: candidates are: typedef class Konsole::Filter Filter
lib/Filter.h:58: error:                 class Konsole::Filter
lib/Filter.cpp:93: error: expected constructor, destructor, or type conversion before ‘*’ token
make[1]: *** [Filter.o] Error 1
make[1]: Leaving directory `/usr/local/src/cool-retro-term/qmltermwidget'
make: *** [sub-qmltermwidget-make_first-ordered] Error 2

**Comment by Swordfish90** [comment]
Hi, this is sadly a known problem which is happening on very few configurations #175 . In the referenced issue there is a workaround to get it working (we still have to investigate the problem tough).
I'm closing this and marking it as a duplicate, if you have updates please post them in #175 .
