### ISSUE TITLE
User Login Shell Not Used on Mac OS X Yosemite

### ISSUE THREAD

**Issue by niedzielski** [Swordfish90/cool-retro-term#231]
I've changed my login shell via `chsh -s` from the default, `/bin/bash`, to Bash 4 via Homebrew, `/usr/local/bin/bash`. This appears to function properly with Apple's Terminal app. I can see the default is set properly by running `dscl /Search -read "/Users/$USER" UserShell`. However, the login shell is not respected by cool-retro-term. The suspect code lives in `qmltermwidget/src/ksession.cpp`:

    QString envshell = getenv("SHELL");
    QString shellProg = envshell != NULL ? envshell : "/bin/bash";
    session->setProgram(shellProg);

Note: `/etc/passwd` does not contain the user login shell on OS X.

**Comment by Swordfish90** [comment]
Hi, @niedzielski in the snippet you posted you can see that CRT looks for the env variable $SHELL. I'm also using a non default shell (on my linux machines) and the $SHELL values is "/bin/zsh". Could you please check that $SHELL is effectively pointing to "/usr/local/bin/bash"?

**Comment by niedzielski** [comment]
Actually, `chsh` seems to have started working after a reboot :/ Sorry for the false alarm!
