### ISSUE TITLE
I unchecked "show menu bar", now how do I get it back?

### ISSUE THREAD

**Issue by eknorg** [Swordfish90/cool-retro-term#237]
See above. I unchecked the show menu bar option, and the menu bar is gone. However, I don't see any option for getting the menu bar back. Is there a shortcut button I'm missing here?

**Comment by Swordfish90** [comment]
Hi @eknorg. You just need to right click anywhere on the terminal and untick it in the context menu.

**Comment by merijnv** [comment]
The default keyboard shortcut is CTRL-SHIFT-m .
