### ISSUE TITLE
I love you ! 

### ISSUE THREAD

**Issue by mathieujobin** [Swordfish90/cool-retro-term#257]
where is your donation button ?

can you do me a favor and implement split screens?

think of 2,4,6,9 cathodique monitors in a grid ! OMG ! 

should you implement some sort of tabbing as well, please make the split inside the tabs, not the other way around. like iterm2 and terminator, not like terminology.

thanks

**Comment by udha** [comment]
@mathieujobin you can probably achieve that with xmonad or similar as your window manager, have you tried that out?

**Comment by mathieujobin** [comment]
thanks you are right. kwin does that quite easily by just dragging the window to the side or corner.
I went in the advanced window settings and disable window title and borders for this app. works great.

**Comment by josefnpat** [comment]
I have had very good success using `tmux` for split screens, etc :smile:

**Comment by x-a-n-a-x** [comment]
> where is your donation button ?

You could simply create bounties on your favourite [Github Issues](https://github.com/Swordfish90/cool-retro-term/issues) with www.bountysource.com.

For the moment, only two bounties have been created: 
https://www.bountysource.com/teams/crt/issues?tracker_ids=479407
