### ISSUE TITLE
App does not start. "intel_do_flush_locked failed: Invalid argument"

### ISSUE THREAD

**Issue by almejo** [Swordfish90/cool-retro-term#26]
It compiles ok but when i try to run it i get the following message

intel_do_flush_locked failed: Invalid argument

My system:

- Ubuntu 14.04 x86_64
- VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller

**Comment by Swordfish90** [comment]
I'm closing this issue since it is related to a very old version. If it's still valid feel free to contact me.
