### ISSUE TITLE
qt-5.5.x compatibility?

### ISSUE THREAD

**Issue by Ponce** [Swordfish90/cool-retro-term#263]
just tried to run the latest version from git on Slackware with qt-5.5.0.

$ cool-retro-term 
QQmlApplicationEngine failed to load component
qrc:/main.qml:116 Type TerminalContainer unavailable
qrc:/TerminalContainer.qml:37 Type PreprocessedTerminal unavailable
qrc:/PreprocessedTerminal.qml:24 plugin cannot be loaded for module "QMLTermWidget": The plugin '/usr/lib64/qt5/qml/QMLTermWidget/libqmltermwidget.so' uses incompatible Qt library. (5.5.0) [release]

**Comment by a-andreyev** [comment]
@Ponce, archlinux x86_64, qt5 5.5.0 -- no problems. Tried binary packages and building from sources also (aur).

**Comment by baguette** [comment]
I'm also running the latest git version on Slackware (current) with Qt 5.5.1 from alienBOB's repo. It's working fine for me.

**Comment by Ponce** [comment]
I just tried again today splitting qmltermwidget in it's own package and all seems to be fine and dandy...
