### ISSUE TITLE
Full color?

### ISSUE THREAD

**Issue by nasfarley88** [Swordfish90/cool-retro-term#285]
It would be great for this terminal to support 'full' color (even if it's not that realistic). Would allow for things like this: https://vimeo.com/22798433.
##

**Comment by YPetremann** [comment]
This functionality already exist, you can test code from https://gist.github.com/XVilka/8346728.
So should close this ticket.

**Comment by oldkentuckymark** [comment]
It's a pretty simple change.
Please let me know how it works.
https://github.com/oldkentuckymark/cool-retro-term

**Comment by mridlen** [comment]
Set "Chroma Color" to 100% in the options.

**Comment by mathieujobin** [comment]
Thank you !
