### ISSUE TITLE
Hangs on osx when invoking tmux

### ISSUE THREAD

**Issue by degaart** [Swordfish90/cool-retro-term#288]
Hello,

It hangs when I invoke tmux. The effects are still running, and I still can select text, but the keyboard doesn't respond, even to ctrl+C. If I close the window, the window closes correctly, but the app icon stays in the dock and is not responding, and I have to force quit it.

App version: release 1.00 (from https://github.com/Swordfish90/cool-retro-term/releases/download/v1.0.0/cool-retro-term100.dmg)
OS: OS X 10.11.3
Tmux version: 2.2
[Stack trace when it stops responding](http://pastebin.com/FHJgTQtn)

Regards,
##

**Comment by bgold-cosmos** [comment]
FWIW, I just ran into this, and it's an El Capitan-only issue.  It appears to be a bug on Apple's part, there's some discussion here:
https://github.com/tmux/tmux/issues/108

**Comment by ColtonDRG** [comment]
It doesn't happen in the OS X terminal, fwiw

**Comment by degaart** [comment]
Upgrading tmux to version 2.3 fixed the issue
