### ISSUE TITLE
The configuration is not saved

### ISSUE THREAD

**Issue by turing-king** [Swordfish90/cool-retro-term#296]
found that the modified configuration is not saved, every time the first default configuration window opens
##

**Comment by soanvig** [comment]
I found a way to do custom config.
* Create custom configuration and save it. Make sure you use 1-word filename (this may be the main problem). U can use my configuration file as the start-point.
* Now, having the file, open it in some editor and change all preferences you want. % values in settings are 0.0 -- 1.0 values in file. Rasterization is 0/1/2 (ordered as in setting dropdown).
* Save
* Remove your theme from theme list, and import it once more. You will need to remove and import it every time you make a changes to the file.

Here is my file, named mytheme.json:
```
{
  "ambientLight": 0.2,
  "backgroundColor": "#000000",
  "bloom": 0.65,
  "brightness": 0.3,
  "burnIn": 0.20,
  "chromaColor": 0,
  "contrast": 0.9,
  "flickering": 0.1,
  "fontColor": "#71e22f",
  "fontName": "TERMINUS_SCALED",
  "fontWidth": 0.85,
  "frameName": "ROUGH_BLACK_FRAME",
  "glowingLine": 0.15,
  "horizontalSync": 0.30,
  "jitter": 0.1,
  "rasterization": 1,
  "rbgShift": 0,
  "saturationColor": 0,
  "screenCurvature": 0,
  "staticNoise": 0.15,
  "windowOpacity": 1,
  "name": "My theme"
}
```
