### ISSUE TITLE
fatal error: QtDebug: No such file or directory

### ISSUE THREAD

**Issue by PrimordialHelios** [Swordfish90/cool-retro-term#298]
I get an error when trying to compile qmltermwidget. I'm running Fedora 23, GCC version 5.3.1 20160406 (Red Hat 5.3.1-6), and I can't seem to figure out what's wrong. I clone the repo, run `git submodule update --init`, then `qmake`, and then `make`. The full output of make is:

`cd qmltermwidget && make -f Makefile
make[1]: Entering directory '/home/tay/Development/Git/not_mine/cool-retro-term/qmltermwidget'
g++ -c -pipe -Wall -W -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fno-strict-aliasing -fPIC  -DHAVE_POSIX_OPENPT -DHAVE_SYS_TIME_H -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT -I/usr/lib64/qt-3.3/mkspecs/default -I. -Ilib -Isrc -I/usr/lib64/qt-3.3/include -o BlockArray.o lib/BlockArray.cpp
lib/BlockArray.cpp:24:19: fatal error: QtDebug: No such file or directory
compilation terminated.
Makefile:233: recipe for target 'BlockArray.o' failed
make[1]: *** [BlockArray.o] Error 1
make[1]: Leaving directory '/home/tay/Development/Git/not_mine/cool-retro-term/qmltermwidget'
Makefile:28: recipe for target 'sub-qmltermwidget' failed
make: *** [sub-qmltermwidget] Error 2`
##

**Comment by dzaczek** [comment]
I has this same problem and resolved b simple trick 
qmake in fedora 27 generate wrong path , i removed all project files and cloned repo again  
and **replaced qmake to  qmake-qt5**

**Comment by PrimordialHelios** [comment]
Hey, that fixed it! Thanks a bunch!
