### ISSUE TITLE
Window always fullscreen and on top when only using one monitor.

### ISSUE THREAD

**Issue by XS-Nitrogen** [Swordfish90/cool-retro-term#305]
I expect I know why this is, it's just rather annoying: I have an old, small-ish laptop with a 1024x768 native resolution, which I think is the default resolution for CRT.

When I have only one monitor attached, CRT launches in fullscreen and always-on-top, even above its own settings window, and I cannot remove it from fullscreen (The fullscreen menu option and hotkeys do nothing). When a second monitor is attached as an extended desktop, CRT launches in a maximized window rather than fullscreen, and I can open its settings window above itself with no issue.

I'm running Ubuntu MATE 16.04.

Is it possible to change this behavior so it launches maximized rather than in a forced fullscreen state?

**Comment by XS-Nitrogen** [comment]
And everything is now working.

**Comment by Techniv** [comment]
Hi !
I have the same problem here on Debian Jessie 8.6 and Cinnamon 2.2.16.

If I launch the term in widowed all work fine. But if I quit it when it in fullscreen mode, when I relaunch it I can't quit the fullscreen mode. Never.
Same thing if I launch it with an other user.

@XS-Nitrogen, do you do something to solve your problem ?

**Comment by cubizh** [comment]
For those that reach this point and are stuck, the solution for me was to start crt with the arg --fullscreen (from another terminal or launcher) and then right click to deactivate fullscreen mode.
