### ISSUE TITLE
Fedora 24 - g++ Command not found

### ISSUE THREAD

**Issue by t3kg33k** [Swordfish90/cool-retro-term#308]
After running qmake-qt5 && make all seems to run but it looks as if it fails at the g++. One step of the output displays g++ command not found.

[ecrosby@localhost cool-retro-term]$ qmake-qt5 && make
cd qmltermwidget/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/ecrosby/cool-retro-term/qmltermwidget/qmltermwidget.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/ecrosby/cool-retro-term/qmltermwidget'
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DHAVE_POSIX_OPENPT -DHAVE_SYS_TIME_H -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ilib -Isrc -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o BlockArray.o lib/BlockArray.cpp
make[1]: g++: Command not found
Makefile:572: recipe for target 'BlockArray.o' failed
make[1]: *** [BlockArray.o] Error 127
make[1]: Leaving directory '/home/ecrosby/cool-retro-term/qmltermwidget'
Makefile:43: recipe for target 'sub-qmltermwidget-make_first-ordered' failed
make: *** [sub-qmltermwidget-make_first-ordered] Error 2

**Comment by MochaChelotti** [comment]
It looks like you need to install g++ This is available via dnf: 

dnf install gcc-c++

**Comment by t3kg33k** [comment]
That worked.
