### ISSUE TITLE
Missing QT dependencies for Fedora

### ISSUE THREAD

**Issue by tigre-bleu** [Swordfish90/cool-retro-term#311]
Under Fedora 24, when the rpm is installed from OpenSUSE Open Build Service, it is missing some qt dependencies.

I add to manually install the following in order to have a working cool-retro-term:
- qt5-qtquickcontrols
- qt5-qtquick1
- qt5-qtbase 
- qt5-qtdeclarative 
- qt5-qtgraphicaleffects

**Comment by KAMiKAZOW** [comment]
Done: https://build.opensuse.org/package/rdiff/home:KAMiKAZOW:Fedora/cool-retro-term?linkrev=base&rev=2 (you have to use my package for that to take effect).

As a general rule: Don't report packaging bugs to upstream projects. Post a comment under that OBS package or whatever.

Please close this bug now (I'm not an admin here, so I can't do it).

**Comment by tigre-bleu** [comment]
Ok, I close it thanks.
