### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by iad42** [Swordfish90/cool-retro-term#33]
Hi, i got arch and after compiling, as the instruction says, i get seg fault: 
./cool-old-term: line 4: 20249 Segmentation fault      (core dumped) qmlscene -I imports app/main.qml
doing sudo doesnt help, but the string is different:
./cool-old-term: line 4: 20258 Segmentation fault      (core dumped) qmlscene -I imports app/main.qml

Добрый день, получаю сегфолт при компиляции согласно инструции: 
./cool-old-term: line 4: 20249 Segmentation fault      (core dumped) qmlscene -I imports app/main.qml
Запуская от рута executable оставляет ошибку, но изменяет строку, в которой она возникла: 
./cool-old-term: line 4: 20258 Segmentation fault      (core dumped) qmlscene -I imports app/main.qml
Буду благодарен за помощь

**Comment by Swordfish90** [comment]
I'm closing this issue since it was related to a very old version. If it's still valid please reopen it.
