### ISSUE TITLE
Wrong rendering in pixel and strings mode

### ISSUE THREAD

**Issue by constpetrov** [Swordfish90/cool-retro-term#35]
Right part of each symbol not rendered
![snapshot2](https://cloud.githubusercontent.com/assets/435718/3749277/1f70b866-17ea-11e4-8dfa-44ec039ec5eb.png)

**Comment by Swordfish90** [comment]
I'm closing this issue since it is related to a very old version. If it's still valid let me know and I'll reopen it.
