### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by 0nurky** [Swordfish90/cool-retro-term#356]
Hi @Swordfish90 

I am more of a Windows person so my question is, will you be porting cool-retro-term to Windows? I would love to see that.

Thanks.

**Comment by bombcheck** [comment]
More or less a duplicate of #40

**Comment by Endogen** [comment]
Hey @0nurky could you please close the issue - since there already is an issue for that

**Comment by 0nurky** [comment]
@Endogen Okay, I will :+1:

**Comment by thewolf9** [comment]
I figured it out using WSL Windows 10 Pro 1803 

`sudo apt-get update
sudo apt-get upgrade
sudo apt-get install qtchooser qt5-default qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-localstorage libqt5qml-graphicaleffects build-essential qtdeclarative5-dev

git clone --recursive https://github.com/Swordfish90/cool-retro-term.git

cd cool-retro-term
qmake && make
cd ..

sudo mv cool-retro-term /opt/cool-retro-term
sudo ln -s /opt/cool-retro-term/cool-retro-term /usr/sbin/cool-retro-term

export DISPLAY=localhost:0
cool-retro-term &
`

**Comment by h3r** [comment]
Based on all the comments found arround, I wrote a full guide to launch cool retro term under a single double click, without having to launch anything previously or having the background console arround.  [Check it out!](https://gist.github.com/h3r/2d5dcb2f64cf34b6f7fdad85c57c1a45)

**Comment by bombcheck** [comment]
Great, but does this have a huge impact on battery life on mobile devices? Seems that there is not just an app running but a complete virtual maschine in the background?

**Comment by h3r** [comment]
Actually, as far as i know. What you actually installed is a Microsoft custom versión oficial Ubuntu that runs nativelly under Windows OS like antes other app. The main drawback there in tems of battery performance is the fact that you are burning the GPU to run cool-retro-term, even on a regular Linux distro because the whole interface is being re-rendered every frame like any gpu-based game.
https://www.quora.com/How-is-Windows-Subsystem-for-Linux-different-from-running-Linux-on-Windows-in-a-VM

**Comment by mreale** [comment]
Sounds like a good job to a Raspberry pi. I plan to embed the pi _inside_ a 15" LCD monitor and use it like an old crt display... I think that would be cool.

**Comment by bombcheck** [comment]
A Pi? Running windows AND the linux subsystem together???

**Comment by bombcheck** [comment]
LOL, you are right. Just thought to complicated in that moment. :D

**Comment by mreale** [comment]
> A Pi? Running windows AND the linux subsystem together???

of course not! no windows here, just linux.
