### ISSUE TITLE
[Arch Linux

### ISSUE THREAD

**Issue by YanDoroshenko** [Swordfish90/cool-retro-term#370]
I can't find a way to comment on Arch Linux package, so I'll write here. I think that setting TERM variable before the Cool Retro Term start (for example to screen) would be nice as it behaves weirdly with xterm256-color.

**Comment by YanDoroshenko** [comment]
I can't find a way to comment on Arch Linux package, so I'll write here. I think that setting `TERM` variable before the Cool Retro Term start (for example to `screen`) would be nice as it behaves weirdly with `xterm256-color`.

**Comment by parjanya** [comment]
Weirdly... how? In some configurations it works ok with TERM=xterm256-color, in others TERM=vt220, for instance, works better.

**Comment by YanDoroshenko** [comment]
@parjanya Sorry, looks like it was a Vim problem, terminal itself seems fine.
