### ISSUE TITLE
Doesn't build on Debian

### ISSUE THREAD

**Issue by n8cn** [Swordfish90/cool-retro-term#379]
no package.

installed deps: 
apt-get install build-essential qmlscene qt5-qmake qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtgraphicaleffects qml-module-qtquick-dialogs qml-module-qtquick-localstorage qml-module-qtquick-window2

qmake completes; make fails with:
user@host:~/cool-retro-term$ make
cd qmltermwidget/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/user/cool-retro-term/qmltermwidget/qmltermwidget.pro -o Makefile ) && make -f Makefile 
Cannot find file: /home/user/cool-retro-term/qmltermwidget/qmltermwidget.pro.
Makefile:43: recipe for target 'sub-qmltermwidget-make_first-ordered' failed
make: *** [sub-qmltermwidget-make_first-ordered] Error 2

**Comment by ychaouche** [comment]
hello n8cn, I have the same problem. Did you solve yours ? how ?
