### ISSUE TITLE
Installation fails on Ubuntu 10.17

### ISSUE THREAD

**Issue by jeffehobbs** [Swordfish90/cool-retro-term#385]
Installation fails on ubuntu 10.17 with this error:

`Package libqt5qml-graphicaleffects is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source`

What's the best way to satisfy that dependency?

**Comment by badp** [comment]
Is it possible that that package is now [qml-module-qtgraphicaleffects](https://packages.ubuntu.com/artful/qml-module-qtgraphicaleffects)?

**Comment by jeffehobbs** [comment]
Maybe? That seemed promising until actually installing cool-retro-term, then the error becomes:

```jeff@metal-box:~$ sudo apt-get install cool-retro-term
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cool-retro-term : Depends: libqt5qml-graphicaleffects but it is not installable
                   Depends: qtdeclarative5-dialogs-plugin but it is not installable
E: Unable to correct problems, you have held broken packages.```

**Comment by badp** [comment]
Well, yes, qml-module-qtgraphicaleffects is sufficient to build from source, but the .deb package is still referencing a package that doesn't exist.

**Comment by jeffehobbs** [comment]
Yes! After installing qml-module-qtgraphicaleffects, downloading and building from source works perfectly. Thanks very much!
