### ISSUE TITLE
[QUESTION] Terminal Closes right after I open it. Unable to disable this setting.

### ISSUE THREAD

**Issue by NicholasEllul** [Swordfish90/cool-retro-term#386]
After adding the command "cd Documents/CS1" as the startup command in preferences, the app now crashes on startup. Reinstalling it hasn't fixed the issue.

EDIT: I don't think its crashing, I think its because it automatically closes after clean exit of the shell command. However, I can't get into preferences before it closes to disable this command.

**Comment by HAZARDU5** [comment]
Erase everything at `~/Library/Application Support/cool-retro-term` and that should fix it for you.

**Comment by BradenPorter** [comment]
@HAZARDU5 Also trying to run a command in CRT at it's autostart but the terminal closes after the command finishes. Need to keep it open to keep using it. Don't have the folder you specify. Any ideas?

**Comment by xam1d** [comment]
Same issue. tried to add in a command and now it won't stay open long enough / cant get to pref to change it back. The above dir/file  "~/Library/Application Support/cool-retro-term" does not exist.
Tried deleting and reinstalling but the file is obviously kept elsewhere.  running on High Sierra 10.13.1

Last login: Sun May 13 14:46:24 on ttys000
Dustins-MacBook-Pro:~ TK255$ /Volumes/cool-retro-term/cool-retro-term.app/Contents/MacOS/cool-retro-term ; exit;
Using an unsupported variable-width font in the terminal.  This may produce display errors.
default KB_LAYOUT_DIR:  "/Volumes/cool-retro-term/cool-retro-term.app/Contents/MacOS/../PlugIns/QMLTermWidget/kb-layouts"
QObject::connect: No such slot Konsole::TerminalDisplay_QML_46::close()
loadAllColorSchemes
Both point size and pixel size set. Using pixel size.
Using an unsupported variable-width font in the terminal.  This may produce display errors.
Session::run() - program: "cd"
Session::run() - arguments: ("desktop/frotz")
started!
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1561.10.101/AppKit.subproj/NSView.m, line 14480.
Illegal instruction: 4
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by xam1d** [comment]
Bump.

**Comment by xam1d** [comment]
Fixed-

To find the above mentioned file "~/Library/Application Support/cool-retro-term"
Go to finder - User and press CMD+Shift+. 
This will show the hidden User Library folder.

**Comment by durbarroy** [comment]
I had the same problem.
I fixed this by deleting a hidden directory that had the QML information
rm -r ~/.local/share/cool-retro-term/

**Comment by NicholasEllul** [comment]
The suggestions above should fix the issue
