### ISSUE TITLE
[Bounty] Make cool-retro-term a usable terminal on macOS.

### ISSUE THREAD

**Issue by antanst** [Swordfish90/cool-retro-term#408]
I love this app, however certain issues prohibit me from using it as my main terminal on macOS, and from what I've seen I'm not alone.

May I suggest any interested people gather up and contribute to a nice bounty for the following issues, in order for macOS to become a first class citizen? The issues I'm referring to are:

#252 
#378 
#240 (I would be fabulus to use a unicode bitmap font like GNU Unifont)
#271 (hide mouse when typing)

@Swordfish90 Any preference as to how we can handle the bounty?

**I'm pledging $100 to bootstrap this, either USD or Bitcoin.**

**Comment by hackbox** [comment]
+1 for $50

**Comment by koniarisgiwrgos** [comment]
I can help too for $20

**Comment by viktorsec** [comment]
@antanst I believe you should create a [https://www.bountysource.com/teams/crt/issues](Bountysource issue) and perhaps link it here.

**Comment by antanst** [comment]
Thanks for the suggestion; I can't find a way to create a bountysource issue from their site, and I'm still waiting for @Swordfish90 to say the preferred method of handling this.

**Comment by viktorsec** [comment]
@antanst Bountysource is stated as the preferred method of handling this in the [readme](https://github.com/Swordfish90/cool-retro-term/blob/master/README.md#donations).

**Comment by antanst** [comment]
Missed that! I just put a $100 [bounty](https://www.bountysource.com/issues/53422547-bounty-make-cool-retro-term-a-usable-terminal-on-macos) at BountySource.

**Comment by pazos** [comment]
Hey @antanst: I'm interested in the bounty, but I'm willing to do the job anyways. I love this application. I made a few comments on those specific issues. All of those seem feasible, but I need to find time to read (and hack) the code 👍 

Other cool stuff would be:

- rules for deploy app bundle / dmg disk buried in the project file
- support for other languages (setting a transifex account or something like that would be awesome)
- detect if the application is busy running a process and show a warning if you click exit (like if you are on a ssh session)

and for extra bells and whistles: support different keyboard layouts and "typical" terminal sounds.
make all configurable.

**Comment by antanst** [comment]
Hey @pazos ,

The bounty still stands, so if you're going to do the work you may as well claim it :-)

Your suggestions are not bad either.

**Comment by pazos** [comment]
Hey, I did a few tests today to fix the behaviour of the keyboard on mac (and hopefully enable the use of different layouts).

You can track the changes on https://github.com/pazos/cool-retro-term

When I have something usable I will ask for testers before submitting a pull request.

**Comment by maxbrito** [comment]
Hello, can we have the CTRL+C and CTRL+V options as available on the OSX terminal?

It makes life so easy to just copy and paste like in all other normal windows.

**Comment by lpar** [comment]
I'd just like to point out that in the interim, you can pick up [Cathode for the Mac](https://itunes.apple.com/us/app/cathode/id499233976?mt=12&ign-mpt=uo%3D4) for $5. It's closed source, but it works well.

**Comment by lraulin** [comment]
Why doesn't this include support for other keyboard layouts? That's the main/only thing making it unusable for me on Mac, and I'd be happy to give some money to anyone who can fix it. The other issues would be nice to have fixed, but aren't quite as important to me. There's an issue for it here. If there's a bounty for it, I'll make a pledge for it.

https://github.com/Swordfish90/cool-retro-term/issues/451

Cathode is ok, but I still like CRT (omg, how did I just now realize why it was named Cool Retro Term) better, because it has more/nicer themes and is more configurable.

But I use the Programmer Dvorak keyboard layout. Interestingly, the top row (numbers and symbols) work as they should for my layout, but all the other keys come out as standard Qwerty. I also find it interesting that it has no problem using Hangul (the Korean alphabet) when I switch to a Korean layout, although that isn't really helpful in any way.

**Comment by lraulin** [comment]
@pazos I installed your fork using the build instructions for Brew, and there doesn't seem to be any difference. But keep up the good work! If you get it work, I'll contribute $20.

**Comment by find1dream** [comment]
@lraulin

Temporary solutions for using programmer dvorak (or others) on Mac os: 
1. Choose your keyboard input source as Australian (Depending on your keyboard, you should try another one if the result is not desired. )
2. Install Karabiner-elements
3. Import programmer dvorak from https://pqrs.org/osx/karabiner/complex_modifications/?q=programmer
4. Enjoy
