### ISSUE TITLE
Can I run crt on WSL using Xming without requiring the original terminal to continue?

### ISSUE THREAD

**Issue by RainyDayMatt** [Swordfish90/cool-retro-term#457]
I open up the WSL Ubuntu Bash, export DISPLAY=:0, and then fire up ./cool-retro-term; this works perfectly, but it by necessity crashes the CRT if I close the bash. Any tips on avoiding this?

**Comment by SDoradus** [comment]
using `nohup` seems to work for me, although it's sometimes works and other times does not.
