### ISSUE TITLE
Is the Cathode App anything to do with cool Retro Term?

### ISSUE THREAD

**Issue by develroo** [Swordfish90/cool-retro-term#468]
I came across this 'promotion' of an app which looks remarkably similar to CRT but makes no attribution to it.

http://www.secretgeometry.com/apps/cathode/

Are they co-opting the code without respecting the GPL?

Curious...

**Comment by Swordfish90** [comment]
Nope. Those are two different projects, and as ttdota was saying Cathode is actually older. :)
