### ISSUE TITLE
Power Line fonts?

### ISSUE THREAD

**Issue by Orionx86** [Swordfish90/cool-retro-term#476]
https://github.com/powerline/fonts

Can we integrate so we can get working zsh prompts? I looked into how its done today and looks like it requires to build into the app rather than use the systems existing font store.

**Comment by Swordfish90** [comment]
With 1.1.0 you are able to use any system font so you can install them separately.

**Comment by cvuorinen** [comment]
@Swordfish90 what is the criteria by which it filters the system fonts? I am not seeing all my fonts in the dropdown menu. Not even all monospaced fonts are there.

**Comment by mccollam** [comment]
@cvuorinen at least for me in Linux, it appears to look in /usr/share/fonts but not in the local user font cache.  So it seems that they must be truly system fonts rather than just installed fonts.

**Comment by fopor** [comment]
For me, it works with I open it from my terminal:
![image](https://user-images.githubusercontent.com/29164832/106779633-f1b62000-6625-11eb-899f-ae1711dbf7cb.png)

But will not work if I open it directly from the .desktop or with 'terminator -e "cool-retro-term"' :
![image](https://user-images.githubusercontent.com/29164832/106779833-232eeb80-6626-11eb-9fc9-b7ccc77b5261.png)

Any tip on how to investigate this?
