### ISSUE TITLE
Implement missing xterm sequences (Neovim support)

### ISSUE THREAD

**Issue by LunarLambda** [Swordfish90/cool-retro-term#484]
The following fixes should be ported from QTermWidget to QMLTermWidget:

DECSCUSR is not supported.
https://github.com/Swordfish90/cool-retro-term/issues/481

Fixed in https://github.com/lxqt/qtermwidget/pull/51

Window resizing is not supported. This breaks Neovim on startup.
https://github.com/Swordfish90/cool-retro-term/issues/328#issuecomment-272470907
https://github.com/neovim/neovim/issues/3245#issuecomment-134957160

Fixed in https://github.com/lxqt/qtermwidget/pull/113

A temporary workaround for Neovim users: 
Neovim works in Cool Retro Term if run from a screen or tmux session.

**Comment by Swordfish90** [comment]
Could you please give a spin to the unstable branch (both CRT and qmltermwidget)? I merged all the upstream changes so those should be included.

**Comment by LunarLambda** [comment]
I'm guessing this can be closed now. Neovim seems to run without any issues (Version 1.0.1, on Antergos)
