### ISSUE TITLE
Border not rendered properly

### ISSUE THREAD

**Issue by badunit** [Swordfish90/cool-retro-term#491]
The border of terminal is not rendered correctly, all other functions seems works properly, but when i add screen curvature it render a strange border around the terminal.

**Screenshots and screenfetch output to show you the issue.**

**Default Amber Profile**
![1](https://user-images.githubusercontent.com/44651201/50562804-a24ee880-0d17-11e9-813e-b8ad2a6d5d8c.png)

**Monochrome Green Profile**
![2](https://user-images.githubusercontent.com/44651201/50562805-a24ee880-0d17-11e9-8e14-714f640fbbaa.png)

**IBM Dos Profile**
![3](https://user-images.githubusercontent.com/44651201/50562910-b2b39300-0d18-11e9-8cfd-07222f5ef9c5.png)

I have downloaded the package from Pamac, and have this issue.
I have download dependencies, then compiled from github, but the issue is still be here.

Ask me if you need extra info from my system.

**Comment by Swordfish90** [comment]
Mmmh... It seems your gpu is not fond of the new frame shader. Could you share what's printed on stdout when launching crt? Using --verbose might be useful.

**Comment by doughsay** [comment]
I'm seeing this after the new update too; I'm also on Manjaro.

I have a GTX 1070 and am using the official Nvidia drivers (current version: 1:415.25-0)

here's the output from running crt with --verbose:

```
$ cool-retro-term --verbose
default KB_LAYOUT_DIR:  "/usr/lib/qt/qml/QMLTermWidget/kb-layouts"
QObject::connect: No such slot Konsole::TerminalDisplay_QML_48::close()
loadAllColorSchemes
qml: Adding system font:  Bitstream Vera Sans Mono
qml: Adding system font:  DejaVu Sans Mono
qml: Adding system font:  Droid Sans Mono
qml: Adding system font:  Fira Code
qml: Adding system font:  Fira Code Light
qml: Adding system font:  Fira Code Medium
qml: Adding system font:  Fira Code Retina
qml: Adding system font:  Fira Mono
qml: Adding system font:  Fira Mono Medium
qml: Adding system font:  Hack
qml: Adding system font:  Inconsolata
qml: Adding system font:  Liberation Mono
qml: Adding system font:  Monospace
qml: Adding system font:  Nimbus Mono PS
qml: Adding system font:  Noto Mono
qml: Adding system font:  PowerlineSymbols
qml: Adding system font:  xos4 Terminus
qml: Adding system font:  Bitstream Vera Sans Mono
qml: Adding system font:  DejaVu Sans Mono
qml: Adding system font:  Droid Sans Mono
qml: Adding system font:  Fira Code
qml: Adding system font:  Fira Code Light
qml: Adding system font:  Fira Code Medium
qml: Adding system font:  Fira Code Retina
qml: Adding system font:  Fira Mono
qml: Adding system font:  Fira Mono Medium
qml: Adding system font:  Hack
qml: Adding system font:  Inconsolata
qml: Adding system font:  Liberation Mono
qml: Adding system font:  Monospace
qml: Adding system font:  Nimbus Mono PS
qml: Adding system font:  Noto Mono
qml: Adding system font:  PowerlineSymbols
qml: Adding system font:  xos4 Terminus
file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
Both point size and pixel size set. Using pixel size.
qml: Loading settings: {
  "fps": 0,
  "x": 55,
  "y": 56,
  "width": 1625,
  "height": 994,
  "windowScaling": 1,
  "showTerminalSize": true,
  "fontScaling": 1,
  "fontNames": [
    "TERMINUS_SCALED",
    "APPLE_II",
    "COMMODORE_PET"
  ],
  "showMenubar": false,
  "bloomQuality": 0.5,
  "burnInQuality": 0.5,
  "useCustomCommand": false,
  "customCommand": ""
}{
  "backgroundColor": "#000000",
  "fontColor": "#ff8100",
  "flickering": 0.1,
  "horizontalSync": 0.08,
  "staticNoise": 0.1198,
  "chromaColor": 0.2483,
  "saturationColor": 0.2483,
  "screenCurvature": 0.3,
  "glowingLine": 0.2,
  "burnIn": 0.2517,
  "bloom": 0.5538,
  "rasterization": 0,
  "jitter": 0.1997,
  "rbgShift": 0,
  "brightness": 0.5,
  "contrast": 0.7959,
  "ambientLight": 0.2,
  "windowOpacity": 1,
  "fontName": "TERMINUS_SCALED",
  "fontWidth": 1,
  "margin": 0.5
}
```

**Comment by Swordfish90** [comment]
I've been able to reproduce the issue using a nvidia gpu. Fix commited. Thank you guys for spotting that.

**Comment by acc3ssd** [comment]
I've been having a similar issue using cool-retro-term 1.2 installed from the Ubuntu repositories (see attached screenshot). The Snap version works fine, but is out of date. I'm running Ubuntu 24.10 with an NVIDIA GeForce RTX 4070 SUPER graphics card. Any idea how to fix it?

![Image](https://github.com/user-attachments/assets/089afde6-b76a-438d-9977-a1ffcfd31d17)
