### ISSUE TITLE
Font is unreadable - any idea why?

### ISSUE THREAD

**Issue by dht** [Swordfish90/cool-retro-term#505]
MacOS Mojave 10.14.2
cool-retro-term 1.1.1
Downloaded & installed of DMG
I've tried changing the fonts and profiles, with similar results.

![screen shot 2019-02-05 at 17 37 07](https://user-images.githubusercontent.com/137832/52284293-cfbd3080-296c-11e9-91ff-7da888ef2537.png)

**Comment by Swordfish90** [comment]
This looks like a duplicate of #502 ... Can you confirm it?
