### ISSUE TITLE
Fast/Slow Burn-in as an option

### ISSUE THREAD

**Issue by neo-anderson** [Swordfish90/cool-retro-term#516]
Hi!
Thanks for creating this awesome terminal.

One of my favorite features of cool-retro-term was the slow burn-in effect. I noticed that the effect is different in the latest release and saw this in the log: "Faster and burn in effect"

Is it possible to provide a setting to switch fast/slow burn-in effect in the next release?

**Comment by Swordfish90** [comment]
I'm glad you are enjoying it.

Don't worry, it's "faster" because it requires less resources to be computed. :)

You can still change it's duration in settings.

**Comment by neo-anderson** [comment]
Aah. Faster as in better :) 👍
