### ISSUE TITLE
snap install issue

### ISSUE THREAD

**Issue by antoniosap** [Swordfish90/cool-retro-term#528]
sudo snap install cool-retro-term_1.1.1_amd64.snap --dangerous --devmode
[sudo] password di antonio: 
error: This revision of snap "cool-retro-term_1.1.1_amd64.snap" was published using classic
       confinement and thus may perform arbitrary system changes outside of the security sandbox
       that snaps are usually confined to, which may put your system at risk.
       If you understand and want to proceed repeat the command including --classic.

and now ?

**Comment by Swordfish90** [comment]
Hi, there is no longer need for those command line arguments. Only classic confinement is required, so you should just type:

sudo snap install cool-retro-term --classic
