### ISSUE TITLE
cannot read 

### ISSUE THREAD

**Issue by xgz123** [Swordfish90/cool-retro-term#550]
![屏幕快照 2019-09-12 下午8 21 16](https://user-images.githubusercontent.com/15977162/64783891-74ef5580-d59b-11e9-906d-e6c1655d83ca.png)

MacOS majave.
on retina screen everything is ok. but cannot not use in external dell display.

**Comment by xgz123** [comment]
font issue

**Comment by Kenny417** [comment]
What font issue? How do you fix this?

**Comment by xgz123** [comment]
by changing it.
