### ISSUE TITLE
Nemo's "open in terminal" does not open in current folder but $HOME instead

### ISSUE THREAD

**Issue by srj-github** [Swordfish90/cool-retro-term#572]
I believe that a fix like this one is required https://github.com/gnunn1/tilix/issues/162#issuecomment-199329035

**Comment by srj-github** [comment]
Thank you but I have not used this terminal for ages.
I'll close the issue.

**Comment by smnski** [comment]
I found a much easier solution for this problem.

Go to local/share/nemo/actions and create a someName.nemo_action file with the following code:

[Nemo Action]
Name=name for this action here
Comment=some optional comment here
Exec=cool-retro-term --workdir "%F"
Icon-Name=cool-retro-term
Selection=Any
Extensions=dir;

Now you can open any directory in the cool retro terminal from the right click menu.
