### ISSUE TITLE
cool-retro-term: ftbfs with GCC-10

### ISSUE THREAD

**Issue by alexmyczko** [Swordfish90/cool-retro-term#581]
Please see here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957100

**Comment by xtaran** [comment]
JFYI: FTBFS is Debian slang and means "Fails to build from source".

**Comment by Swordfish90** [comment]
Hi guys. I merged on master the pull request which should fix the issue (https://github.com/Swordfish90/qmltermwidget/pull/27). Could you please give it a go on GCC 10 and let me know if everything is working fine now?

**Comment by alexmyczko** [comment]
Works! https://mentors.debian.net/package/cool-retro-term/
