### ISSUE TITLE
resource-hungry

### ISSUE THREAD

**Issue by codenoid** [Swordfish90/cool-retro-term#585]
my dued, it's cool, but

![Screenshot from 2020-05-06 12-53-18](https://user-images.githubusercontent.com/14269809/81142159-0b441180-8f99-11ea-9cb2-4c9627c336de.png)

OS : Ubuntu 20.04

**Comment by aconitumnapellus** [comment]
Maybe this is just on the snap version, because i did install the arch package and i dont have that problem at all.. What did you do in the terminal while taking this screenshot?

**Comment by codenoid** [comment]
> What did you do in the terminal while taking this screenshot?

nothing, just htop

**Comment by codenoid** [comment]
oh man, this just weird 

![Screenshot from 2020-05-06 20-43-26](https://user-images.githubusercontent.com/14269809/81184187-50d4fe80-8fda-11ea-99b7-f8bb408b5622.png)

**Comment by codenoid** [comment]
```
sudo snap remove snap
```
