### ISSUE TITLE
Icon missing from snap install (ubuntu 20.04)

### ISSUE THREAD

**Issue by mightydeadunicorn** [Swordfish90/cool-retro-term#593]
In `cool-retro-term.desktop` there is currently:

`Icon=cool-retro-term`

Thus GNOME desktop entry is just default white cog.

**Comment by alexmyczko** [comment]
Anything you don't like about the official ubuntu 20.04 package?

**Comment by mightydeadunicorn** [comment]
I actually forgot about this issue, forgive my bad memory. Closing
