### ISSUE TITLE
Bash autocomplete behaves weirdly

### ISSUE THREAD

**Issue by stefan-reich** [Swordfish90/cool-retro-term#601]
Hi, when I press Tab in a CRT session (connected to BASH on a freshly installed Ubuntu 18.04 server), I get this: [Screenshot](https://botcompany.de/images/1102947)

(Screen fills with random lines.)

I think I've seen it fixed on another server, but forgot how I did that.

With another terminal (sakura), Tab key works fine without printing any of those lines.

Any ideas?

Edit: The problem is suddenly gone. Hmm. I'll leave this open for a bit, maybe someone has some input anyway?

**Comment by baxy750** [comment]
This may be related to another TAB issue which is [issue 598](https://github.com/Swordfish90/cool-retro-term/issues/598)

**Comment by stefan-reich** [comment]
Thanks for the comment. I think it probably wasn't to CRT, just to the server in question. After logging in again, it seems fine. I'm closing this. Thanks
