### ISSUE TITLE
Can't See Settings Because Font and Background are the Same Color

### ISSUE THREAD

**Issue by AgentLoneStar007** [Swordfish90/cool-retro-term#689]
The title says it all. I use the KDE-Plasma desktop environment on EndeavourOS(which is Arch-based).
![image](https://user-images.githubusercontent.com/57960152/145439308-e2ed101d-9877-47f3-92d6-40ae9d6502d7.png)

**Comment by hawk78** [comment]
I have th same problem on kubuntu. This happens when you enable a dark colorscheme. The settings dialog bakground shall follow the system's background color or the system font color shall be ignored.

**Comment by AgentLoneStar007** [comment]
But I'm using a dark theme on KDE Plasma, with white font. Wouldn't that mean that the background would be dark?

**Comment by AgentLoneStar007** [comment]
Alright, I followed your suggestion and switched to a light theme on Plasma. As long as I have the light theme on I can edit the settings for the terminal. The only catch is I have to endure the horrifying pain of my retinas being liquified by my screen.

(Oh, and a suggestion: please add the ability to edit keybinds for the terminal. I really want to change the Copy/Paste keybinds to their proper Ctrl+C/Ctrl+V bindings.)

**Comment by 4qx** [comment]
I just reverted to [previous version](https://i9-drive.mycozy.cloud/public?sharecode=J3Q9DTjZOv7h), thankfully still had it in pacman cache.

**Comment by wd5gnr** [comment]
Quick workaround: launch like this:

QT_QUICK_CONTROLS_STYLE=Material cool-retro-term

Ugly, but you can read it. This bug is in a few different places.

**Comment by ssrublev** [comment]
> Quick workaround: launch like this:
> 
> QT_QUICK_CONTROLS_STYLE=Material cool-retro-term
> 
> Ugly, but you can read it. This bug is in a few different places.

Thank you very much! I am having this issue in Fedora 39 KDE with CRT 1.2.0. Menu is irreadable and I can't make border frame black, only white (nvidia card).
