### ISSUE TITLE
How can i run this on Windows system?

### ISSUE THREAD

**Issue by qRainBirdp** [Swordfish90/cool-retro-term#696]
I really like this project, but how can i run it on Windows system?

**Comment by jeijunn** [comment]
> I really like this project, but how can i run it on Windows system?

You may try WSLg(Windows Subsystem for Linux with GUI) on Windows11 or WSL on Windows 10 with a XServer such like Xming.

**Comment by qRainBirdp** [comment]
> > I really like this project, but how can i run it on Windows system?
> 
> You may try WSLg(Windows Subsystem for Linux with GUI) on Windows11 or WSL on Windows 10 with a XServer such like Xming.

Is this like running this project with a virtual？Maybe I can just install another Ubuntu system. Thanks!
