### ISSUE TITLE
cool-retro-term - no multiple commands by -e arguments and terminal closing

### ISSUE THREAD

**Issue by D3vil0per** [Swordfish90/cool-retro-term#728]
Hello,
when the user provides a command by the application, for example `cool-retro-term -e neofetch`, the terminal closes after its execution. Usually, for keeping the terminal opened, a further command calling a shell can be typed. The problem is that, `-e` argument seems to not take more than one command, where the first command is parsed by cool-retro-term and the second command is executed by the terminal where I typed `cool-retro-term -e <command1>; <command2>`.

I also tried to wrap the two commands after `-e` argument inside double or single quotes but it is not working. Can you please implement the possibility to set more than 1 command by using `-e` argument? I think this could be done on `main.cpp` file by managing better the `cmdList` variable.

Furthermore, if I try to setting a startup command on the GUI settings -> Advanced, I have the same issue because, if I use a command, as `neofetch`, after the execution the terminal closes. If I insert two commands as `neofetch;bash`, they are not executed.

**Comment by ali1234** [comment]
You can do this by invoking a shell as the program, and then asking it to run the commands you want:

`cool-retro-term -e /bin/sh -c '<command1>; <command2>'`

To prevent the terminal closing after the command(s) you can do this:

`cool-retro-term -e /bin/sh -c 'neofetch; echo "Press any key to exit"; read x'`

**Comment by D3vil0per** [comment]
Thanks!

**Comment by DeutscheGabanna** [comment]
This functionality doesn't seem equivalent to running commands on a normal cool-retro-term manually.
While typing commands manually into the console, every command works. But when doing `cool-retro-term --default-settings -e bash -c 'command; read x', only rudimentary commands are supported like `ls` and such. Typing custom commands results in something like this:

```
Traceback (most recent call last):
  File "/usr/local/bin/filetags", line 2752, in <module>
    main()
  File "/usr/local/bin/filetags", line 2662, in main
    get_tags_from_files_and_subfolders(
  File "/usr/local/bin/filetags", line 1245, in get_tags_from_files_and_subfolders
    assert(os.path.isdir(startdir))
AssertionError
```

**Comment by DeutscheGabanna** [comment]
> EDIT after some testing: `cool-retro-term -e /bin/bash` - this loads current user's bash profile correctly, even without commands like `source ~/.bashrc`. I can run any program from this like I could from starting the terminal manually.
> 
> However, if you try to launch cool-retro-term like @D3vil0p3r suggests - using `cool-retro-term -e /bin/bash -c 'source ~/.bashrc; echo whatever'` the profile never gets loaded. So if you try to run an application from this new window, it will most likely fail as it has no $PATH or any other environmental variables.

I still have this problem in 2024 :)
