### ISSUE TITLE
The qmlscene freezes on right mouse click

### ISSUE THREAD

**Issue by staniek** [Swordfish90/cool-retro-term#75]
Generally ubercool!
Minor thing: On right mouse click the window freezes. Then, X11 isn't accessible for mouse/keyboard for me and only killing the qmlscene process helps.

opensuse 13.1, KDE:/Qt5/openSUSE_13.1

**Comment by Astrr** [comment]
I have this issue on Manjaro, KDE+i3 as WM. Couldn't solve this even after wiping my ssd and reinstalling OS. Freezes after 1-10 seconds of cursor being on right click menu or settings.

**Comment by Astrr** [comment]
Solved by installing proprietary gpu drivers
