### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by tgerczei** [Swordfish90/cool-retro-term#76]
Hey! I pretty much fell in love with this at first glance. However, I'd like to be able to install it properly and would therefore like to have an ebuild for Gentoo available. I'll do it myself at some point later in time but as I've never done one from scratch before and won't have a suitable machine on my hands soon enough, it might take a while - so an experienced volunteer would be most welcome. :)

**Comment by happysmash27** [comment]
tgerczei: Your overlay is no longer working.

**Comment by happysmash27** [comment]
Nevermind, I needed to update the overlay file from wget https://www.gerczei.eu/files/gerczei.xml -O /etc/layman/overlays/gerczei.xml.

**Comment by tgerczei** [comment]
@happysmash27 OK - I think this has also been mentioned in the README. Please let me know if that's incorrect or insufficient!

**Comment by happysmash27** [comment]
It seems the ebuild is now using an outdated EAPI, giving errors whenever I run emerge: 

```
 * ERROR: x11-terms/cool-retro-term-9999::gerczei failed (depend phase):
 *   qmake-utils.eclass: unsupported EAPI=5
 *
 * Call stack:
 *                     ebuild.sh, line 616:  Called source '/var/lib/layman/gerczei/x11-terms/cool-retro-term/cool-retro-term-9999.ebuild'
 *   cool-retro-term-9999.ebuild, line   7:  Called inherit 'git-r3' 'qmake-utils' 'eutils'
 *                     ebuild.sh, line 317:  Called __qa_source '/usr/portage/eclass/qmake-utils.eclass'
 *                     ebuild.sh, line 112:  Called source '/usr/portage/eclass/qmake-utils.eclass'
 *            qmake-utils.eclass, line  20:  Called die
 * The specific snippet of code:
 *   [[ ${EAPI:-0} == [012345] ]] && die "qmake-utils.eclass: unsupported EAPI=${EAPI:-0}"
 *
 * If you need support, post the output of `emerge --info '=x11-terms/cool-retro-term-9999::gerczei'`,
 * the complete build log and the output of `emerge -pqv '=x11-terms/cool-retro-term-9999::gerczei'`.
 * Working directory: '/usr/lib64/python3.6/site-packages'
 * S: '/var/tmp/portage/x11-terms/cool-retro-term-9999/work/cool-retro-term-9999'
```

**Comment by tgerczei** [comment]
Thank You for reporting! Yes, that's known and I have [this issue](https://git.gerczei.eu/tgerczei/gentoo-overlay/issues/2) open. That said, as per [this pull request](https://github.com/Swordfish90/cool-retro-term/pull/566) this package had been superseded. It hasn't been merged yet, though, so the official documentation wouldn't let you know right now. At any rate, please emerge "x11-terms/cool-retro-term-1.1.1::gentoo" instead. If you still need the bleeding edge -9999 ebuild, please tell me or just patch it via a pull request and I'll be happy to merge it.
