### ISSUE TITLE
trying to replitate cool asmr that uses cathode term 

### ISSUE THREAD

**Issue by alavaelian** [Swordfish90/cool-retro-term#788]
Is this one https://www.youtube.com/watch?v=iG6M-vt-4JY.
the sound of the fan an the hard drive is from youtube, the one that i am trying to do is the beep sound when the guy write a character and  also want to emulate the dynamicly generated text in screen

**Comment by franalbani** [comment]
Try this ones:
* https://mynoise.net/NoiseMachines/dataCenterNoiseGenerator.php
* https://mynoise.net/NoiseMachines/fanNoiseGenerator.php

**Comment by alavaelian** [comment]
thanks so much dude that not where the ones that i was looking for , it was the beeping one . but thenks so much that  links would be of so much help
