### ISSUE TITLE
(Feature request) Anachronistic full-color mode

### ISSUE THREAD

**Issue by ghost** [Swordfish90/cool-retro-term#79]
The monochrome is neat for most purposes but some roguelikes which would otherwise be amazing in cool-old-term are broken due to the lack of color support.

Would love to have an option to enable full (or at least 8 or 16 including the bold attrib color changes) color support to make roguelike games integrate with cool-old-term better.

Unfortunately I know nothing about qt so I don't know where to begin implementing this.

**Comment by protman** [comment]
It looks as though some of the settings are not applied until we close and reopen. Chroma Color is one.
