### ISSUE TITLE
How to import Themes on (MacOS)

### ISSUE THREAD

**Issue by pretzelmonster** [Swordfish90/cool-retro-term#799]
Hi, I don't know how to use the nice 3rd party template examples from the Wiki. When copying one into a text file, Cool Retro Term doesn't allow to import the file. So it seems only a certain extension seems to allow the import. What is this (also CRT doesn't work) or what am I doing wrong?
Thanks for the cool terminal, reminds me of Commodore C64 and PET times!!!

**Comment by kevinyjiang** [comment]
It works with .json files

**Comment by pretzelmonster** [comment]
Ah, yes, that was it. Thanks!!!
