### ISSUE TITLE
Anyone interested in FreeBSD support?

### ISSUE THREAD

**Issue by alex0x08** [Swordfish90/cool-retro-term#802]
Hi, 
just patched your project for FreeBSD:
![bsd-klingon2](https://github.com/Swordfish90/cool-retro-term/assets/3603492/abfaf109-f18e-4983-932d-aa00d481164a)

Currently this is just a 'hack&proof' state, far from real patch. 
So my question is there any other *BSD users interested in 'cool-retro-term' support on BSD systems?  

P.S. Don't put much attention on Klingon glyph - this was added as a joke ;)

**Comment by alexmyczko** [comment]
https://www.freshports.org/x11/cool-retro-term ?

**Comment by ehaupt** [comment]
It is already available as ports for most BSD's. See [repology](https://repology.org/project/cool-retro-term/packages). If you have additional patches upstream would surely be interested in a pull request.

For instance, on FreeBSD you can install the FreeBSD [port](https://www.freebsd.org/ports/) via pkg:
```sh
pkg install cool-retro-term
```

or build via ports:
```sh
cd /usr/ports/x11/cool-retro-term
make install clean
```

**Comment by alex0x08** [comment]
> It is already available as ports for most BSD's. See [repology](https://repology.org/project/cool-retro-term/packages). If you have additional patches upstream would surely be interested in a pull request.

Yep, already mentioned this, so closing issue.
